# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
